name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.10 ]

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker-compose build --no-cache
      - name: Start services
        run: |
          docker-compose up -d orthanc1 orthanc2
      - name: Run Tests
        run: |
          docker-compose run --rm test